apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuxt-app.fullname" . }}
  labels:
    {{- include "nuxt-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nuxt-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
